logging:
  level:
    root: INFO

fire-res:
  threads-count: 4
  presets:
    default-presets-path: ./presets/default/
    custom-presets-path: ./presets/custom/
  primary-stage:
    title: Генератор отчетов о тестировании на огнестойкость
    min-width: 600
    min-height: 510
    resizable: true
    maximized: true
  general-properties:
    env-temperature:
      default-value: 21
      min-value: 0
      max-value: 100
    time:
      default-value: 50
      min-value: 1
      max-value: 1000


